export const DEFAULT_CATEGORIES = [
  {
    id: 'food',
    name: 'Food & Dining',
    icon: 'restaurant',
    color: '#FF6B6B',
    type: 'expense',
  },
  {
    id: 'transport',
    name: 'Transportation',
    icon: 'car',
    color: '#4ECDC4',
    type: 'expense',
  },
  {
    id: 'shopping',
    name: 'Shopping',
    icon: 'cart',
    color: '#FFD93D',
    type: 'expense',
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    icon: 'game-controller',
    color: '#A8E6CF',
    type: 'expense',
  },
  {
    id: 'bills',
    name: 'Bills & Utilities',
    icon: 'receipt',
    color: '#FF8B94',
    type: 'expense',
  },
  {
    id: 'health',
    name: 'Healthcare',
    icon: 'medical',
    color: '#95E1D3',
    type: 'expense',
  },
  {
    id: 'education',
    name: 'Education',
    icon: 'school',
    color: '#F38181',
    type: 'expense',
  },
  {
    id: 'travel',
    name: 'Travel',
    icon: 'airplane',
    color: '#AA96DA',
    type: 'expense',
  },
  {
    id: 'investment',
    name: 'Investment',
    icon: 'trending-up',
    color: '#FCBAD3',
    type: 'expense',
  },
  {
    id: 'other',
    name: 'Other',
    icon: 'ellipsis-horizontal',
    color: '#A8DADC',
    type: 'expense',
  },
];

export const INCOME_CATEGORIES = [
  {
    id: 'salary',
    name: 'Salary',
    icon: 'briefcase',
    color: '#00B894',
    type: 'income',
  },
  {
    id: 'investment_income',
    name: 'Investment',
    icon: 'trending-up',
    color: '#00CEC9',
    type: 'income',
  },
  {
    id: 'part_time',
    name: 'Part Time',
    icon: 'time',
    color: '#55EFC4',
    type: 'income',
  },
  {
    id: 'bonus',
    name: 'Bonus',
    icon: 'gift',
    color: '#81ECEC',
    type: 'income',
  },
  {
    id: 'other_income',
    name: 'Others',
    icon: 'cash',
    color: '#74B9FF',
    type: 'income',
  },
];

export const APP_COLORS = {
  primary: '#00B894',
  secondary: '#00B894',
  background: '#F8F9FA',
  cardBackground: '#FFFFFF',
  text: '#2D3436',
  textSecondary: '#636E72',
  textLight: '#B2BEC3',
  border: '#DFE6E9',
  success: '#00B894',
  warning: '#FDCB6E',
  danger: '#D63031',
  income: '#00B894',
  expense: '#D63031',
  overlay: 'rgba(0, 0, 0, 0.5)',
};